<template>
  <p
    class="
      mb-2
      text-primary-light
      dark:text-primary-dark
      font-medium
      uppercase
      tracking-wider
    "
  >
    <slot>Category</slot>
  </p>
</template>